### PR TITLE
Add TV-Cards Passthrough Section

### PR DESCRIPTION
**Pull request by yehia2amer**
**Description**
⚒️Providing details on how to passthrough TV-Cards. As currently USB Passthrough also works with PCI Devices.

**⚙️ Type of change**

- [x] 📄 Add documentation

### CODE REVIEW

**Comment by stavros-k** [comment]
Please create a new file in the same directory name it how ever you want eg `notes.md`
the first sentence should the the title as a h1 (`# TV-Cards Passthrough`).
And paste the rest underneath.

All other files are automatically generated and will prune everything you written there on the next update

**Comment by Ornias1993** [comment]
I prefer this going into community guides or at least a general guide, instead of having things that are, basically, general information going into seperate Apps.

**Review by Ornias1993 — CHANGES_REQUESTED** [review]
I prefer this going into community guides or at least a general guide, instead of having things that are, basically, general information going into seperate Apps.

I also want to be made clear that we officially offer no support for PCI(-E) devices at the moment.

**Comment by yehia2amer** [comment]
@Ornias1993 I created another pull request https://github.com/truecharts/pub/pull/18 in the community guides as instructed.

**Pull request closed without merging**
